
import type { AnyData } from './types';

export const mockData: AnyData[] = [
  // Users
  {
    __backendId: "user_1",
    id: "user_1",
    module: "users",
    type: "user",
    username: "admin",
    password: "admin",
    role: "Admin",
    created_at: new Date().toISOString(),
  },
  {
    __backendId: "user_2",
    id: "user_2",
    module: "users",
    type: "user",
    username: "cashier",
    password: "cashier",
    role: "Cashier",
    created_at: new Date().toISOString(),
  },
  // Products
  {
    __backendId: "prod_1",
    id: "product_1",
    module: "inventory",
    type: "product",
    product_code: "P001",
    barcode: "8850006300104",
    product_name: "Coca-Cola",
    category: "အချိုရည်",
    supplier: "Myanmar Golden Star",
    unit: "ဘူး",
    cost: 500,
    price: 800,
    quantity: 150,
    reorder_level: 20,
    image_url: "🥤",
    price_history: JSON.stringify([
        { date: "2024-06-15T10:00:00Z", old_price: 750, new_price: 800 },
        { date: "2024-05-01T10:00:00Z", old_price: 700, new_price: 750 }
    ]),
    created_at: new Date().toISOString(),
  },
  {
    __backendId: "prod_2",
    id: "product_2",
    module: "inventory",
    type: "product",
    product_code: "P002",
    barcode: "8850772101019",
    product_name: "Lay's Classic Potato Chips",
    category: "မုန့်များ",
    supplier: "Myanmar Golden Star",
    unit: "ထုပ်",
    cost: 800,
    price: 1200,
    quantity: 80,
    reorder_level: 15,
    image_url: "🍟",
    created_at: new Date().toISOString(),
  },
  {
    __backendId: "prod_3",
    id: "product_3",
    module: "inventory",
    type: "product",
    product_code: "P003",
    barcode: "9556025100108",
    product_name: "Mamee Monster Noodle Snack",
    category: "မုန့်များ",
    supplier: "Myanmar Golden Star",
    unit: "ထုပ်",
    cost: 200,
    price: 300,
    quantity: 200,
    reorder_level: 50,
    image_url: "🍜",
    created_at: new Date().toISOString(),
  },
  {
    __backendId: "prod_4",
    id: "product_4",
    module: "inventory",
    type: "product",
    product_code: "P004",
    barcode: "4902102072618",
    product_name: "Ovaltine Soy Milk",
    category: "အချိုရည်",
    supplier: "DKSH Myanmar",
    unit: "ဘူး",
    cost: 600,
    price: 1000,
    quantity: 90,
    reorder_level: 20,
    image_url: "🥛",
    created_at: new Date().toISOString(),
  },
   {
    __backendId: "prod_5",
    id: "product_5",
    module: "inventory",
    type: "product",
    product_code: "P005",
    product_name: "Royal-D Electrolyte Beverage",
    category: "အချိုရည်",
    supplier: "DKSH Myanmar",
    unit: "ထုပ်",
    cost: 150,
    price: 250,
    quantity: 300,
    reorder_level: 50,
    image_url: "🍹",
    created_at: new Date().toISOString(),
  },
  {
    __backendId: "prod_6",
    id: "product_6",
    module: "inventory",
    type: "product",
    product_code: "P006",
    product_name: "Milo Cereal",
    category: "အစားအစာ",
    supplier: "DKSH Myanmar",
    unit: "ဗူး",
    cost: 3500,
    price: 4500,
    quantity: 40,
    reorder_level: 10,
    image_url: "🥣",
    created_at: new Date().toISOString(),
  },
  {
    __backendId: "prod_7",
    id: "product_7",
    module: "inventory",
    type: "product",
    product_code: "P007",
    product_name: "UFC Refresh Coconut Water",
    category: "အချိုရည်",
    supplier: "Myanmar Golden Star",
    unit: "ဘူး",
    cost: 900,
    price: 1500,
    quantity: 60,
    reorder_level: 15,
    image_url: "🥥",
    created_at: new Date().toISOString(),
  },
   {
    __backendId: "prod_8",
    id: "product_8",
    module: "inventory",
    type: "product",
    product_code: "P008",
    product_name: "Premier Coffee Mix",
    category: "ကော်ဖီ",
    supplier: "DKSH Myanmar",
    unit: "ထုပ်",
    cost: 2500,
    price: 3200,
    quantity: 5,
    reorder_level: 10,
    image_url: "☕",
    created_at: new Date().toISOString(),
  },
  // Customers
  {
    __backendId: "cust_1",
    id: "customer_1",
    module: "customers",
    type: "customer",
    customer_name: "U Ba",
    customer_phone: "09111111111",
    loyalty_points: 125,
    created_at: new Date().toISOString(),
  },
  {
    __backendId: "cust_2",
    id: "customer_2",
    module: "customers",
    type: "customer",
    customer_name: "Daw Mya",
    customer_phone: "09222222222",
    loyalty_points: 45,
    created_at: new Date().toISOString(),
  },
  {
    __backendId: "cust_3",
    id: "customer_3",
    module: "customers",
    type: "customer",
    customer_name: "Ko Aung",
    customer_phone: "09333333333",
    loyalty_points: 320,
    created_at: new Date().toISOString(),
  },

  // Suppliers
  {
    __backendId: "supp_1",
    id: "supplier_1",
    module: "suppliers",
    type: "supplier",
    supplier_name: "Myanmar Golden Star",
    supplier_phone: "09123456789",
    supplier_email: "contact@mgs.com.mm",
    supplier_address: "Yangon, Myanmar",
    supplier_products: JSON.stringify([
      { category: "အချိုရည်", products: ["Coca-Cola", "Sprite", "Fanta", "Shark Energy Drink"] },
      { category: "မုန့်များ", products: ["Lay's Chips", "Potaeto Chips", "Mamee Noodle Snack", "Oishi Prawn Crackers"] }
    ]),
    created_at: new Date().toISOString(),
  },
  {
    __backendId: "supp_2",
    id: "supplier_2",
    module: "suppliers",
    type: "supplier",
    supplier_name: "DKSH Myanmar",
    supplier_phone: "09987654321",
    supplier_email: "info@dksh.com.mm",
    supplier_address: "Mandalay, Myanmar",
    supplier_products: JSON.stringify([
      { category: "အချိုရည်", products: ["Ovaltine", "Milo", "Dutch Mill Yoghurt Drink"] },
      { category: "အစားအစာ", products: ["Milo Cereal", "Koko Krunch Cereal"] },
      { category: "ကော်ဖီ", products: ["Premier Coffee", "Nescafe Coffee"] }
    ]),
    created_at: new Date().toISOString(),
  },
];